import { Header } from '@/components/Header'
import './globals.css'

export const metadata = {
  title: 'Rafael Prudente - Deputado Federal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className="relative">
        <div className='gsap-scroll'>
          <Header/>
            {children}
        </div>
      </body>
    </html>
  )
}
